# Generated by Django 5.1.6 on 2025-10-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('Celulares', 'Celulares'), ('Relojes Inteligentes', 'Relojes Inteligentes'), ('Accesorios SM', 'Accesorios'), ('Consolas', 'Consolas'), ('Juegos', 'Juegos'), ('Accesorios GM', 'Accesorios'), ('Hardware', 'Hardware'), ('Perifericos', 'Perifericos'), ('TV, Audio y Video', 'TV, Audio y Video'), ('Teléfonos', 'Teléfonos'), ('Seguridad', 'Seguridad'), ('Fotografia y Filmacion', 'Fotografia y Filmacion'), ('Remeras', 'Remeras'), ('Pantalones', 'Pantalones'), ('Zapatillas', 'Zapatillas'), ('Gorras', 'Gorras')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Smartphones', 'Smartphones'), ('Games', 'Games'), ('Informática', 'Informática'), ('Electrónica', 'Electrónica'), ('Indumentaria o Ropa', 'Indumentaria o Ropa')], default='Electrónica', max_length=100),
        ),
    ]
